
package view;

import java.awt.HeadlessException;
import java.io.IOException;
import javax.swing.JOptionPane;
import controller.*;
import java.io.File;
import java.io.FileOutputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hoang
 */
public class Config_db extends javax.swing.JFrame {
    
    
    /** Creates new form config_db */
    public Config_db() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_dbUsername = new javax.swing.JTextField();
        txt_dbName = new javax.swing.JTextField();
        btn_dbConnect = new javax.swing.JButton();
        btn_dbExit = new javax.swing.JButton();
        txt_dbPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Config Database");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("Tên Database");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("CẤU HÌNH DATABASE");

        txt_dbUsername.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txt_dbUsername.setText("sa");

        txt_dbName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txt_dbName.setText("QLBH04");

        btn_dbConnect.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btn_dbConnect.setText("Cập nhập");
        btn_dbConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dbConnectActionPerformed(evt);
            }
        });

        btn_dbExit.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btn_dbExit.setText("Thoát ứng dụng");
        btn_dbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dbExitActionPerformed(evt);
            }
        });

        txt_dbPassword.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txt_dbPassword.setText("123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_dbConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_dbExit))
                            .addComponent(txt_dbName)
                            .addComponent(txt_dbUsername)
                            .addComponent(txt_dbPassword))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_dbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dbConnect)
                    .addComponent(btn_dbExit))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_dbConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dbConnectActionPerformed
        // TODO add your handling code here:
        String dbName = txt_dbName.getText();
        String dbUsername = txt_dbUsername.getText();
        String dbPassword = txt_dbPassword.getText();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        h_Utils h = new h_Utils();
        if(dbName.equals("") || dbUsername.equals("") || dbPassword.equals("")){
            JOptionPane.showMessageDialog(this, "Không để trống ô");
        } else if(dbName.contains(",") || dbUsername.contains(",") || dbPassword.contains(",")){
            JOptionPane.showMessageDialog(this, "Dữ liệu nhập không hợp lệ");
        } else if(dbPassword.substring(0, 1).equals(" ") || dbPassword.substring(dbPassword.length()-1, dbPassword.length()).equals(" ")){
            JOptionPane.showMessageDialog(this, "Mật khẩu không được bắt đầu hoặc kết thúc bằng khoảng trắng");
        } else {
            try {
                FileOutputStream fos = new FileOutputStream(new File("dbSaveConfig_hg.dat").getAbsolutePath());
                fos.write(h.getEncrypted(dbName.trim()+','+dbUsername.trim()+','+dbPassword));
                fos.close();
                JOptionPane.showMessageDialog(this, "Hoàn tất nhập cấu hình, bắt đầu kết nối...");
                
                h.init_dbConfig();
                Connection con = DBUtils.getConnection();
                ResultSet rs = con.createStatement().executeQuery("select * from Nhanvien");
                new view.Login().setVisible(true);
                dispose();
               
            } catch (HeadlessException | IOException | NoSuchAlgorithmException | NoSuchPaddingException 
                    | InvalidKeyException | IllegalBlockSizeException | BadPaddingException | SQLException | NullPointerException  e)  {
                System.out.println(e);
                JOptionPane.showMessageDialog(this,"Không kết nối được SQL Server, xin kiểm tra lại cấu hình");
            }
        }
        
        
    }//GEN-LAST:event_btn_dbConnectActionPerformed

    
    private void btn_dbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dbExitActionPerformed
        // TODO add your handling code here:
        int hoi=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (hoi==JOptionPane.YES_OPTION){
            System.exit(0); 
    }//GEN-LAST:event_btn_dbExitActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config_db().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dbConnect;
    private javax.swing.JButton btn_dbExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_dbName;
    private javax.swing.JPasswordField txt_dbPassword;
    private javax.swing.JTextField txt_dbUsername;
    // End of variables declaration//GEN-END:variables

}
